// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/transformer/v1/transformer.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformRequest) Reset() {
	*x = TransformRequest{}
	mi := &file_proto_transformer_v1_transformer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformRequest) ProtoMessage() {}

func (x *TransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transformer_v1_transformer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformRequest.ProtoReflect.Descriptor instead.
func (*TransformRequest) Descriptor() ([]byte, []int) {
	return file_proto_transformer_v1_transformer_proto_rawDescGZIP(), []int{0}
}

func (x *TransformRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type TransformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Byline        string                 `protobuf:"bytes,2,opt,name=byline,proto3" json:"byline,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	HtmlContent   string                 `protobuf:"bytes,4,opt,name=htmlContent,proto3" json:"htmlContent,omitempty"`
	PlaintText    string                 `protobuf:"bytes,5,opt,name=plaintText,proto3" json:"plaintText,omitempty"`
	Tokens        []*Token               `protobuf:"bytes,6,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformResponse) Reset() {
	*x = TransformResponse{}
	mi := &file_proto_transformer_v1_transformer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformResponse) ProtoMessage() {}

func (x *TransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transformer_v1_transformer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformResponse.ProtoReflect.Descriptor instead.
func (*TransformResponse) Descriptor() ([]byte, []int) {
	return file_proto_transformer_v1_transformer_proto_rawDescGZIP(), []int{1}
}

func (x *TransformResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TransformResponse) GetByline() string {
	if x != nil {
		return x.Byline
	}
	return ""
}

func (x *TransformResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *TransformResponse) GetHtmlContent() string {
	if x != nil {
		return x.HtmlContent
	}
	return ""
}

func (x *TransformResponse) GetPlaintText() string {
	if x != nil {
		return x.PlaintText
	}
	return ""
}

func (x *TransformResponse) GetTokens() []*Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Start         int32                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End           int32                  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_proto_transformer_v1_transformer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transformer_v1_transformer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_transformer_v1_transformer_proto_rawDescGZIP(), []int{2}
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Token) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Token) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

var File_proto_transformer_v1_transformer_proto protoreflect.FileDescriptor

const file_proto_transformer_v1_transformer_proto_rawDesc = "" +
	"\n" +
	"&proto/transformer/v1/transformer.proto\x12\x0etransformer.v1\"$\n" +
	"\x10TransformRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xce\x01\n" +
	"\x11TransformResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06byline\x18\x02 \x01(\tR\x06byline\x12\x1a\n" +
	"\bimageUrl\x18\x03 \x01(\tR\bimageUrl\x12 \n" +
	"\vhtmlContent\x18\x04 \x01(\tR\vhtmlContent\x12\x1e\n" +
	"\n" +
	"plaintText\x18\x05 \x01(\tR\n" +
	"plaintText\x12-\n" +
	"\x06tokens\x18\x06 \x03(\v2\x15.transformer.v1.TokenR\x06tokens\"E\n" +
	"\x05Token\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x05R\x03end2f\n" +
	"\x12TransformerService\x12P\n" +
	"\tTransform\x12 .transformer.v1.TransformRequest\x1a!.transformer.v1.TransformResponseBPZNgithub.com/neihtq/tap-lingo/services/transformer-service/gen/go/transformer/v1b\x06proto3"

var (
	file_proto_transformer_v1_transformer_proto_rawDescOnce sync.Once
	file_proto_transformer_v1_transformer_proto_rawDescData []byte
)

func file_proto_transformer_v1_transformer_proto_rawDescGZIP() []byte {
	file_proto_transformer_v1_transformer_proto_rawDescOnce.Do(func() {
		file_proto_transformer_v1_transformer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transformer_v1_transformer_proto_rawDesc), len(file_proto_transformer_v1_transformer_proto_rawDesc)))
	})
	return file_proto_transformer_v1_transformer_proto_rawDescData
}

var file_proto_transformer_v1_transformer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_transformer_v1_transformer_proto_goTypes = []any{
	(*TransformRequest)(nil),  // 0: transformer.v1.TransformRequest
	(*TransformResponse)(nil), // 1: transformer.v1.TransformResponse
	(*Token)(nil),             // 2: transformer.v1.Token
}
var file_proto_transformer_v1_transformer_proto_depIdxs = []int32{
	2, // 0: transformer.v1.TransformResponse.tokens:type_name -> transformer.v1.Token
	0, // 1: transformer.v1.TransformerService.Transform:input_type -> transformer.v1.TransformRequest
	1, // 2: transformer.v1.TransformerService.Transform:output_type -> transformer.v1.TransformResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_transformer_v1_transformer_proto_init() }
func file_proto_transformer_v1_transformer_proto_init() {
	if File_proto_transformer_v1_transformer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transformer_v1_transformer_proto_rawDesc), len(file_proto_transformer_v1_transformer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transformer_v1_transformer_proto_goTypes,
		DependencyIndexes: file_proto_transformer_v1_transformer_proto_depIdxs,
		MessageInfos:      file_proto_transformer_v1_transformer_proto_msgTypes,
	}.Build()
	File_proto_transformer_v1_transformer_proto = out.File
	file_proto_transformer_v1_transformer_proto_goTypes = nil
	file_proto_transformer_v1_transformer_proto_depIdxs = nil
}
